version: '3'

services:

  app:
    build:
      context: node
    container_name: app    
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s /docker-entrypoint.sh
    # command:
    #   - node /usr/src/app/index.js
    networks:
      - node-network
    tty: true   
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - "./init.sql:/docker-entrypoint-initdb.d/1.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: leandromeira/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  
    
networks:
    node-network:
      driver: bridge 